apiVersion: v1
kind: Service
metadata:
  name: arun-flask-service
  namespace: arun-devops
spec:
  selector:
    app: arun-flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
