apiVersion: apps/v1
kind: Deployment
metadata:
  name: arun-flask-deployment
  namespace: arun-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arun-flask
  template:
    metadata:
      labels:
        app: arun-flask
    spec:
      containers:
        - name: arun-flask-container
          image: arun-jenkins-flask-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
